-- local ruled = require("ruled")
-- Set Firefox to always map on the tag named "2" on screen 1.
-- ruled.client.append_rule {
--     rule       = { class = "Firefox"     },
--     properties = { screen = 1, tag = "2" }
-- }
